### ISSUE TITLE
audioProfileLevelIndication - not accepting 0x29 Hex (Decimal=41) i.e. AAC@L2

### ISSUE THREAD

**Issue by richardbushell** [Dash-Industry-Forum/Conformance-and-reference-source#6]
We currently have a MPD which throws an error in the DASH Conformance Validator Log online.
Here is our MPD: http://living.tv/mob/ibeani_i4_mcstdlownew.mpd

Our file contains: audioProfileLevelIndication - 0x29 Hex (Decimal=41)
Which I think is AAC@L2
I think this is AAC Low Complexity (Stereo), but I am no expert!

But it throws this error:
Validate_IODS: ISMA expects no-capability(0xFF) or Hi-Quality@L1/L2 (0x0E, 0x0F) or AAC@L4 (0x2a) or HE-AAC@L2 (0x2c) for audioProfileLevelIndication

Shouldn't AAC@L2 be acceptable?

Richard

**Comment by waqarz** [comment]
Hi,
The error is actually one line below: ValidateIODSAtom: must have at least one Class_ES_ID_IncTag . The lines above are warnings that can be ignored.
These are however not DASH-specific conformance issues, rather related to elementary streams.

**Comment by richardbushell** [comment]
Are you saying that if there is an ID tag then it would display the warning lines above relating to audioProfileLevel? This seems odd.

So, is AAC@L2 (0x29) a valid audioProfileLevel? And if so shouldn't this be added to this list of ISMA expects... (in the message shown)

**Comment by richardbushell** [comment]
Also, just for clarification, I am unsure of the correct current standard.
Under ISO/IEC 14496-3:2009, should it be:
0x29   AAC Profile L2
OR is this correct:
0x51	  AAC Profile L2
whiich I saw referenced here:
http://itscj.ipsj.or.jp/sc29/open/29view/29n14342t.doc
Which is the correct values under the latest standard?

**Comment by waqarz** [comment]
The problem is I am not sure what this error means "ValidateIODSAtom: must have at least one Class_ES_ID_IncTag", what I do know is that someone at ISMA implemented this rule for a good reason, and we need to either:
- Address this issue in the content, or
- Come to conclusion that this rule is not valid and should be removed.
I cannot do the second item myself and would need some help to come to this conclusion.

**Comment by jeanlf** [comment]
My understanding is that ISMA used to have a conformance rule on BIFS/OD tracks being present (quoting ISM spec 1.0, "ISMA compliant content, when stored in files, will contain the minimal BIFS and OD streams as described in Appendix E."), but this is not a requirement from ISO/IEC 14496-14, since ODs/IODs may be empty in MPEG-4 systems. I think you can remove this warning

regarding AAC profiles the document you found is the MPEG-2 signaling of AAC profiles, not MP4 file one.
